services:
  rdb:
    image: mysql:8.0.36
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_bin
    ports:
      - "3306:3306"
    volumes:
      - rdb-data:/var/lib/mysql
      - ./mysql/conf.d:/etc/mysql/conf.d
    environment:
      LANG: C.UTF-8
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: dev
      MYSQL_PASSWORD: pass
      MYSQL_DATABASE: biblog

  rdb-test:
    image: mysql:8.0.36
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_bin
    ports:
      - "3307:3306"
    volumes:
      - rdb-test-data:/var/lib/mysql
      - ./mysql/conf.d:/etc/mysql/conf.d
    environment:
      LANG: C.UTF-8
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: dev
      MYSQL_PASSWORD: pass
      MYSQL_DATABASE: biblog_test

volumes:
  rdb-data:
    driver: local
  rdb-test-data:
    driver: local
